language: python
cache: pip
sudo: false
python:
  - "3.6"
env:
  - REQ=""
matrix:
  include:
    - python: "2.7"
      env: REQ="Django>=1.7,<1.8"
    - python: "2.7"
      env: REQ="Django>=1.8,<1.9"
    - python: "2.7"
      env: REQ="Django>=1.9,<1.10"
    - python: "2.7"
      env: REQ="Django>=1.10,<1.11"
    - python: "2.7"
      env: REQ="Django>=1.11,<2.0"
    - python: "3.4"
      env: REQ="Django>=1.11,<2.0"
    - python: "3.4"
      env: REQ="Django>=2.0,<2.1"
    - python: "3.5"
      env: REQ="Django>=1.11,<2.0"
    - python: "3.5"
      env: REQ="Django>=2.0,<2.1"
    - python: "3.5"
      env: REQ="Django>=2.1,<2.2"
    - python: "3.6"
      env: REQ="Django>=1.11,<2.0"
    - python: "3.6"
      env: REQ="Django>=2.0,<2.1"
    - python: "3.6"
      env: REQ="Django>=2.1,<2.2"
    - python: "3.6"
      env: REQ="https://github.com/django/django/archive/master.zip"
  allow_failures:
    - env: REQ="https://github.com/django/django/archive/master.zip"
install:
  - pip install $REQ django-js-asset
script: cd tests && ./manage.py test testapp && cd ..
